After we are done creating our service layer we need to get our controllers in place. First we have our basic book
controller that can either return a list of all books or show a selected book.

[source,groovy]
.grails-app/controllers/demo/BookController.groovy
----
include::{sourceDir}/grails-app/controllers/demo/BookController.groovy[]
----

Next is our Favourites controller that can return a list of books we have favourited, and our action to favourite a
desired book.

[source,groovy]
.grails-app/controllers/demo/BookFavouriteController.groovy
----
include::{sourceDir}/grails-app/controllers/demo/BookFavouriteController.groovy[]
----
<1> Call our custom favourite book finder
<2> Call our custom `findAll`
<3> Call to save our favourite

Then we have our `SuccessfullyLoggedInController` which we will make use of to set a flash message for when we have
successfully logged in.

NOTE: The path to our `SuccessfullyLoggedInController.index` is our `frontendCallbackUrl` in `application.groovy`.

[source,groovy]
.grails-app/controllers/demo/SuccessfullyLoggedInController.groovy
----
include::{sourceDir}/grails-app/controllers/demo/SuccessfullyLoggedInController.groovy[]
----
<1> So we can access the user that logged in
<2> Get user attributes for display message